### PR TITLE
Use LRU caches during index build to limit memory consumption

### LINKED ISSUE #227: How to control memory usage during `CREATE INDEX`?
### What happened?

When creating an index over 1B+ records I'm seeing memory usage increase linearly, seemingly unbounded. Is this expected/is there a way to control memory usage?

### pgvectorscale extension affected

_No response_

### PostgreSQL version used

17.4

### What operating system did you use?

Ubuntu 24.04

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash

```

### How can we reproduce the bug?

```bash
Run `CREATE INDEX` over a very large corpus of vectors and monitor the memory consumption.
```

### Are you going to work on the bugfix?

None

### PR DESCRIPTION
**Pull request by tjgreen42**
Convert `QuantizedVectorCache` and `BuilderNeighborCache` into LRUs whose space consumption is governed by `maintenance_work_mem`.  This fixes #227 and lays a piece of the groundwork needed for parallel indexing.

### CODE REVIEW

File: pgvectorscale/src/access_method/graph/neighbor_store.rs [hunk 1]
```diff
@@ -1,76 +1,146 @@
...
+
+    /// Estimate of the size of an entry in the cache in bytes.
+    pub fn size(num_neighbors: usize, has_labels: bool) -> usize {
+        std::mem::size_of::<Self>()
+            + num_neighbors * std::mem::size_of::<NeighborWithDistance>()
+            + if has_labels {
+                std::mem::size_of::<LabelSet>() + 4
+            } else {
+                0
+            }
```
Comment (syvb) [inline pgvectorscale/src/access_method/graph/neighbor_store.rs:42]: This shouldn't be added; the size of the `LabelSet` is already included in `std::mem::size_of::<Self>()` (the size of an `Option<T>` is at least the size of `T`).

File: pgvectorscale/src/access_method/graph/neighbor_store.rs [hunk 2]
```diff
@@ -1,76 +1,146 @@
...
-#[derive(Default)]
+///
+pub struct NeighborCacheEntry {
+    pub labels: Option<LabelSet>,
+    pub neighbors: Vec<NeighborWithDistance>,
+}
+
+impl NeighborCacheEntry {
+    pub fn new(labels: Option<LabelSet>, neighbors: Vec<NeighborWithDistance>) -> Self {
+        Self { labels, neighbors }
```
Comment (syvb) [inline pgvectorscale/src/access_method/graph/neighbor_store.rs:31]: maybe call `Vec::shrink_to_fit` on the neighbors here to make the size estimation below correct?
